version: '3.9'

services:
  backend:
    build:
      context: ./backend/job_parser
    volumes:
      - ./backend/job_parser:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=job_parser.settings
      - DB_NAME=
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=db
      - DB_PORT=5432
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    depends_on:
      - elasticsearch
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - my_network

  elasticsearch:
    image: elasticsearch:8.14.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
  es_data: